-- ================================================
-- Supabase Schema for teams table
-- Run this in Supabase SQL Editor if creating table manually
-- ================================================

CREATE TABLE IF NOT EXISTS public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  logo_url TEXT,
  description TEXT,
  games TEXT,
  region TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- Allow public read access
CREATE POLICY "Allow public read access on teams"
  ON public.teams FOR SELECT
  USING (true);

-- Allow full access for anon/authenticated API requests
CREATE POLICY "Allow full access on teams"
  ON public.teams FOR ALL
  USING (true);
